### ISSUE TITLE
Typescript breaks WindiCSS

### ISSUE THREAD

**Issue by tcosmo** [oekazuma/sveltekit-typescript-windicss#2]
Very weird issue here.

Consider the following `index.svelte`:

```html
<script lang="ts">
	let a = 2;
</script>

<div>
	<div class="mt-10 w-full bg-red-500 flex items-center justify-center">hey</div>
</div>
```

As expected, you'll get:

![Screenshot 2022-03-05 at 17 58 56](https://user-images.githubusercontent.com/7616128/156894872-54adfd4d-331a-4d9c-b906-dde03b313f44.png)

Now, use a type annotation in your ts code:

```html
<script lang="ts">
	let a: Number = 2;
</script>

<div>
	<div class="mt-10 w-full bg-red-500 flex items-center justify-center">hey</div>
</div>
```

Now WindiCSS does not work:
![Screenshot 2022-03-05 at 17 59 46](https://user-images.githubusercontent.com/7616128/156894898-501ba58e-4a95-4c3a-b6ce-87db4fee770a.png)

**Comment by oekazuma** [comment]
This repository is my personal template; for bugs in `svelte-windicss-preprocess`, please open an issue in `svelte-windicss-preprocess`.

I recommend using `vite-plugin-windicss` because `svelte-windicss-preprocess` has many unstable elements, and close this issue.

template using `vite-plugin-windicss`
https://github.com/oekazuma/sveltekit-typescript-windicss-vite
